# Django
django: ./tweeter.sh

# Consul Client Agent
consul: consul agent -bind $PRIVATE_IP_ADDRESS -advertise $PRIVATE_IP_ADDRESS -join consul_server -data-dir /data -config-dir /etc/consul.d -enable-local-script-checks
